package com.marcoromanofinaa.jazzlogs.core.outbox;

public enum OutboxEventType {
    ALBUM_EDITORIAL_EMBEDDING_SYNC_REQUESTED,
    TRACK_EDITORIAL_EMBEDDING_SYNC_REQUESTED,
    ARTIST_EDITORIAL_EMBEDDING_SYNC_REQUESTED
}
